/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop2p;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author aryam
 */
public class BorrowdBill extends javax.swing.JFrame {
    private static int Bill_no;
    private String Type;
    private Date date;
    private String book;
    Connection con=main.CreateConnection();
    Statement st;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form BorrowdBill
     */
    public BorrowdBill() {
        initComponents();
    }
    
    
       DefaultListModel mod=new DefaultListModel();
   public  void BorrowBill(int Bill_no,String book, String Type, Date date,String totl,String pricee) {
        this.Bill_no=Bill_no;
       tot.setText(totl);
         btype.setText(Type);
          conl.setText(book+"                  "+pricee);
       billno.setText("#"+String.valueOf(Bill_no));
        curnd.setText(date.toString());
        try{
        Statement st2=con.createStatement();
          ResultSet rs2=st2.executeQuery("Select * from borrow_table where Bill_no='"+Bill_no+"'");
              while(rs2.next()){

              dued.setText(rs2.getString("Due_date"));
   }}
         catch(SQLException e){
        JOptionPane.showMessageDialog(null,e.getMessage());
       }
            
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        curnd = new javax.swing.JLabel();
        export = new javax.swing.JButton();
        btype = new javax.swing.JLabel();
        tot = new javax.swing.JLabel();
        conl = new javax.swing.JLabel();
        billno = new javax.swing.JLabel();
        logout1 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dued = new javax.swing.JLabel();
        conti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 253, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop2p/Logobill11.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 70, -1));

        jLabel2.setText("********************************************");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 230, -1));

        jLabel3.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        jLabel3.setText("THANK YOU ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel4.setText("Borrowed Book:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel5.setText("Price:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel7.setText("Total Price:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        curnd.setFont(new java.awt.Font("SimSun", 0, 10)); // NOI18N
        curnd.setText("Today's date:");
        jPanel1.add(curnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        export.setBackground(new java.awt.Color(255, 255, 247));
        export.setFont(new java.awt.Font("SimSun", 0, 10)); // NOI18N
        export.setText("Export ");
        export.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        jPanel1.add(export, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 50, -1));

        btype.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jPanel1.add(btype, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, 20));

        tot.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jPanel1.add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 60, 10));

        conl.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jPanel1.add(conl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 220, 70));

        billno.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jPanel1.add(billno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        logout1.setBackground(new java.awt.Color(255, 255, 247));
        logout1.setFont(new java.awt.Font("SimSun", 0, 10)); // NOI18N
        logout1.setText("Logout");
        logout1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });
        jPanel1.add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 50, -1));

        exit.setBackground(new java.awt.Color(255, 255, 247));
        exit.setFont(new java.awt.Font("SimSun", 0, 10)); // NOI18N
        exit.setText("Exit");
        exit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 50, -1));

        jLabel11.setText("------------------------------------------------");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 230, -1));

        jLabel12.setText("------------------------------------------------");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 230, -1));

        jLabel6.setFont(new java.awt.Font("SimSun", 0, 10)); // NOI18N
        jLabel6.setText("* Please make sure to return the book on ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 250, -1));

        dued.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        dued.setText("DUE");
        jPanel1.add(dued, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 100, -1));

        conti.setBackground(new java.awt.Color(255, 255, 247));
        conti.setFont(new java.awt.Font("SimSun", 0, 10)); // NOI18N
        conti.setText("Continue Shopping");
        conti.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        conti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contiActionPerformed(evt);
            }
        });
        jPanel1.add(conti, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
      login l=new login();
      l.setVisible(true);
            this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_logout1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
     JFrame frame=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to Exit?","Exit",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
      String Bill_Type="Borrow bill";
       ;
        
       String totalAmount=tot.getText();
        try {
            FileWriter Writer = new FileWriter("BorrowBills.txt",true);
            Writer.write(Bill_Type+"#"+Bill_no+" \n"+totalAmount+"\n-----------------------------\n");
            Writer.close();
            JOptionPane.showMessageDialog(null, "Bill Exporting Successful");    
        }
        catch (HeadlessException | IOException e) {
       JOptionPane.showMessageDialog(null, "Bill Exporting Failed");}
        
// TODO add your handling code here:
    }//GEN-LAST:event_exportActionPerformed

    private void contiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contiActionPerformed
       JFCart c=new JFCart();
        c.setVisible(true);
            this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_contiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
      File billsFile = new File("BorrowBills.txt");
      if (billsFile.createNewFile()) {
        System.out.println("File created: " + billsFile.getName());
      }
    }  
         catch (IOException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowdBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowdBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowdBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowdBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrowdBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billno;
    private javax.swing.JLabel btype;
    private javax.swing.JLabel conl;
    private javax.swing.JButton conti;
    private javax.swing.JLabel curnd;
    private javax.swing.JLabel dued;
    private javax.swing.JButton exit;
    private javax.swing.JButton export;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout1;
    private javax.swing.JLabel tot;
    // End of variables declaration//GEN-END:variables
}
