/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop2p;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author aryam
 */
public class BoughtBill extends javax.swing.JFrame {
 Connection con=main.CreateConnection();
    private static int Billnum;
    Statement st;
    ResultSet rs;
    Statement st2;
    ResultSet rs2;
    PreparedStatement pst;
    
    /**
     * Creates new form BillJFrame
     */
    public BoughtBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        billno = new javax.swing.JLabel();
        tot = new javax.swing.JLabel();
        curndate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btype = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        npan = new java.awt.Panel();
        pripan = new java.awt.Panel();
        exit = new javax.swing.JButton();
        export = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        conti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 253, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop2p/Logobill11.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 70));

        jLabel2.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        jLabel2.setText("THANK YOU");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 70, -1));

        billno.setFont(new java.awt.Font("Urdu Typesetting", 0, 14)); // NOI18N
        billno.setText("Bill no:");
        jPanel1.add(billno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -5, -1, 30));

        tot.setFont(new java.awt.Font("Urdu Typesetting", 0, 12)); // NOI18N
        tot.setText("Total Price:");
        jPanel1.add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, -1));

        curndate.setFont(new java.awt.Font("Urdu Typesetting", 0, 12)); // NOI18N
        curndate.setText("Today's date :");
        jPanel1.add(curndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("*****************************************");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 120, 300, -1));

        jLabel11.setText("-------------------------------------------");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 230, -1));

        btype.setText("jLabel3");
        jPanel1.add(btype, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel3.setText("Book names");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel4.setText("Price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        npan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        npan.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jPanel1.add(npan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 60, 160));

        pripan.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jPanel1.add(pripan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 30, 150));

        exit.setBackground(new java.awt.Color(255, 255, 247));
        exit.setFont(new java.awt.Font("SimSun", 0, 10)); // NOI18N
        exit.setText("Exit");
        exit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 50, -1));

        export.setBackground(new java.awt.Color(255, 255, 247));
        export.setFont(new java.awt.Font("SimSun", 0, 10)); // NOI18N
        export.setText("Export ");
        export.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        jPanel1.add(export, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 50, -1));

        logout1.setBackground(new java.awt.Color(255, 255, 247));
        logout1.setFont(new java.awt.Font("SimSun", 0, 10)); // NOI18N
        logout1.setText("Logout");
        logout1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });
        jPanel1.add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 50, -1));

        jLabel12.setText("--------------------------------------------");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 230, -1));

        conti.setBackground(new java.awt.Color(255, 255, 247));
        conti.setFont(new java.awt.Font("SimSun", 0, 10)); // NOI18N
        conti.setText("Continue Shopping");
        conti.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        conti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contiActionPerformed(evt);
            }
        });
        jPanel1.add(conti, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        JFrame frame=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to Exit?","Exit",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
         login l=new login();
         l.setVisible(true);
            this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_logout1ActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
    String Bill_Type="Bought bill";
       String Billnu=billno.getText();
        
       String totalAmount=tot.getText();
        try {
            FileWriter Writer = new FileWriter("BoughtBills.txt",true);
            Writer.write(Bill_Type+" \n"+Billnu+" \n"+totalAmount+"\n-----------------------------\n");
            Writer.close();
            JOptionPane.showMessageDialog(null, "Bill Exporting Successful"); 
            
        }
        catch (HeadlessException | IOException e) {
       JOptionPane.showMessageDialog(null, "Bill Exporting Failed");}

        // TODO add your handling code here:
    }//GEN-LAST:event_exportActionPerformed

    private void contiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contiActionPerformed
        JFCart c=new JFCart();
        c.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_contiActionPerformed
      public void setbillno(int no){
           // uu.setText(u);
              this.Billnum=Billnum;
            } 
    
    
    public  void BoughtBill(int Bill_no) {
        try{
            //System.out.print(Bill_no);
                npan.removeAll();
                npan.revalidate();
                npan.repaint();
                npan.setLayout(new java.awt.FlowLayout());
           StringBuilder builder=new StringBuilder();
       st=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
       String query="Select * from billcontents where Bill_no='"+Bill_no+"'";
              rs=st.executeQuery(query);
              rs.last();
              int rows=rs.getRow();
              rs.beforeFirst();
              String[]books=new String[rows];
              ArrayList<String> b=new ArrayList<String>();
       while(rs.next()){
//                         builder.append(rs.getInt("Book_id"));

            for(int i=0;i<1;i++){
               
           books[i]=(rs.getString("bookID"));
               System.out.println(books[i]);
               b.add(books[i]);
               
                }
//               pp.add(books[i]);
            }
           
          btype.setText("Buy Bill");
         // bor.setText(String.valueOf(builder));
       
       for(int i=0;i<b.size();i++){
                         booktitles(b.get(i));
                         System.out.print(b.get(i));
       }
          st2=con.createStatement();
          rs2=st2.executeQuery("Select * from buy_table where Bill_no='"+Bill_no+"'");
              while(rs2.next()){

              tot.setText("Total price : "+rs2.getString("Price"));

             billno.setText("#"+String.valueOf(Bill_no));
             curndate.setText(rs2.getString("purchase_date"));}}
          catch(SQLException e){
        JOptionPane.showMessageDialog(null,e.getMessage());
       }
}
         public void booktitles(String book_id){
          try{
            st=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            String query="Select * from books where bookID='"+book_id+"'";
              rs=st.executeQuery(query);
              while(rs.next()){
                  npan.add(new JLabel(rs.getString("booktitle")));
                  pripan.add(new JLabel(rs.getString("price")));
              }
       }       catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e.getMessage());

}
             
   }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
      File billsFile = new File("BoughtBills.txt");
      if (billsFile.createNewFile()) {
        System.out.println("File created: " + billsFile.getName());
      }
    }  
         catch (IOException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoughtBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoughtBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoughtBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoughtBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoughtBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billno;
    private javax.swing.JLabel btype;
    private javax.swing.JButton conti;
    private javax.swing.JLabel curndate;
    private javax.swing.JButton exit;
    private javax.swing.JButton export;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout1;
    private java.awt.Panel npan;
    private java.awt.Panel pripan;
    private javax.swing.JLabel tot;
    // End of variables declaration//GEN-END:variables
}
